'''版本号'''
__version__ = '0.1.3'
'''作者'''
__author__ = 'centyuan'
'''标题'''
__title__ = 'OcrGather'
'''描述'''
__description__ = 'Some third-party OCR services are encapsulated'
'''链接'''
__url__ = 'https://github.com/centyuan/OcrGather'
'''邮件'''
__email__ = 'centyuan88@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2023-2033 hlyuan'